# 🐍🗄️ Session 13 — SQL depuis Python
## pandas + SQLAlchemy + PostgreSQL

---

## 🎯 Objectifs de cette session

- Comprendre **pourquoi** utiliser SQL depuis Python
- Découvrir ce que sont les **ORM** et pourquoi ils sont importants
- Connecter Python à une base **SQLite** et **PostgreSQL**
- Lire des données avec `pandas.read_sql_query`
- Exécuter des requêtes **JOIN** directement depuis Python
- **Nettoyer** et **transformer** les résultats avec pandas
- **Écrire** des résultats dans la base de données (`to_sql`)
- Exporter les résultats en **CSV**

---

## 📦 Livrables

- Ce notebook `sql_python_s13.ipynb`
- Le fichier `requirements.txt`
- Un fichier CSV exporté depuis Python

---

## 🤔 Partie 1 — Pourquoi faire du SQL depuis Python ?

### Le problème du cloisonnement

Dans la réalité professionnelle, les données ne vivent pas dans des fichiers CSV ni dans des notebooks.  
Elles vivent dans des **bases de données relationnelles** : PostgreSQL, MySQL, SQL Server, Oracle…

En tant qu'analyste ou data scientist, vous avez deux approches :

| Approche | Description | Limitation |
|----------|-------------|------------|
| **GUI (DBeaver, PgAdmin)** | Exécuter des requêtes manuellement, exporter en CSV | Non reproductible, fastidieux, difficile à automatiser |
| **Python + SQL** | Interroger la base, traiter dans pandas, réécrire dans la base | ✅ Reproductible, automatisable, intégrable dans des pipelines |

### Les avantages de SQL depuis Python

1. **Reproductibilité** : un script Python + SQL peut être rejoué à l'identique
2. **Automatisation** : planifier des rapports quotidiens, hebdomadaires
3. **Puissance combinée** : SQL gère la récupération et le filtrage, pandas gère la transformation complexe
4. **Pipelines de données** : ETL (Extract-Transform-Load) complets en Python
5. **Collaboration** : les scripts SQL peuvent être versionnés avec Git
6. **Scalabilité** : traiter des millions de lignes via SQL avant de charger en mémoire

---

### 💡 Le principe : laisser chaque outil faire ce qu'il fait le mieux

```
SQL (dans la base)          Python / pandas (en mémoire)
──────────────────          ────────────────────────────
Jointures multi-tables  →   Transformations complexes
Filtres et agrégations  →   Visualisations
Données volumineuses    →   Machine Learning
Accès concurrent        →   Reporting automatisé
```

---

## 🏗️ Partie 2 — Qu'est-ce qu'un ORM ?

### ORM = Object-Relational Mapper

Un **ORM** est une bibliothèque qui crée une correspondance entre :
- Les **tables** de votre base de données
- Les **classes Python** (objets)

Au lieu d'écrire du SQL brut, vous manipulez des objets Python et l'ORM génère le SQL à votre place.

### Exemple : Sans vs Avec ORM

**Sans ORM (SQL brut) :**
```python
conn.execute("SELECT * FROM customers WHERE city = 'Paris'")
```

**Avec ORM (SQLAlchemy) :**
```python
session.query(Customer).filter(Customer.city == 'Paris').all()
```

### Les ORM Python les plus courants

| ORM | Usage principal | Popularité |
|-----|-----------------|------------|
| **SQLAlchemy** | Polyvalent, data engineering, notebooks | ⭐⭐⭐⭐⭐ |
| **Django ORM** | Développement web (framework Django) | ⭐⭐⭐⭐ |
| **Peewee** | Projets légers et simples | ⭐⭐⭐ |
| **Tortoise ORM** | Asynchrone (FastAPI, asyncio) | ⭐⭐⭐ |

### Pourquoi SQLAlchemy est-il important pour l'analyse de données ?

SQLAlchemy offre **deux niveaux d'utilisation** :

1. **Core** (niveau bas) : écrire du SQL avec Python, mais avec abstraction du moteur  
   → C'est ce qu'utilise `pandas.read_sql_query()` en arrière-plan

2. **ORM** (niveau haut) : mapper tables ↔ classes Python  
   → Utilisé dans les applications web, les pipelines ETL

**Pour l'analyse de données, SQLAlchemy Core est suffisant** :  
il vous permet de :
- Écrire du SQL dans vos notebooks
- Changer de base de données (SQLite → PostgreSQL) en ne changeant qu'une ligne
- Passer les résultats directement à pandas

```
Python (vous écrivez)    SQLAlchemy (abstraction)    Base de données
──────────────────────   ──────────────────────────   ───────────────
pandas.read_sql_query  ← engine = create_engine()  → SQLite
df.to_sql()            ← connection string         → PostgreSQL
                                                   → MySQL
```

---

## 🔌 Partie 3 — Les outils de connexion Python ↔ Base de données

### 3.1 sqlite3 — Le module standard Python

Python intègre nativement le support de SQLite. Pas besoin d'installer quoi que ce soit.

```python
import sqlite3
conn = sqlite3.connect('ma_base.db')  # Connexion directe
cursor = conn.cursor()
cursor.execute("SELECT * FROM customers")
rows = cursor.fetchall()
conn.close()
```

**Avantage** : inclus dans Python, aucune installation  
**Limite** : ne fonctionne qu'avec SQLite, API bas niveau

### 3.2 SQLAlchemy — La couche d'abstraction universelle

```python
from sqlalchemy import create_engine

# SQLite
engine = create_engine('sqlite:///ma_base.db')

# PostgreSQL
engine = create_engine('postgresql+psycopg2://user:password@host:5432/dbname')

# MySQL
engine = create_engine('mysql+pymysql://user:password@host/dbname')
```

**Avantage** : change de base juste en changeant l'URL  
**Intégration parfaite** avec pandas (`read_sql_query`, `to_sql`)

### 3.3 psycopg2 — Le driver PostgreSQL

`psycopg2` est le **driver natif PostgreSQL** pour Python.  
Il est utilisé par SQLAlchemy sous le capot quand vous vous connectez à PostgreSQL.

```python
import psycopg2

conn = psycopg2.connect(
    host='localhost',
    database='my_db',
    user='my_user',
    password='my_password',
    port=5432
)
cursor = conn.cursor()
cursor.execute("SELECT version();")
print(cursor.fetchone())
conn.close()
```

**Note** : En data analysis, on préfère utiliser SQLAlchemy + psycopg2 ensemble :
```python
# psycopg2 est le "moteur", SQLAlchemy est le "volant"
engine = create_engine('postgresql+psycopg2://user:password@localhost:5432/sales_db')
df = pd.read_sql_query("SELECT * FROM customers", engine)
```

### 3.4 Résumé des URL de connexion

| Base de données | URL SQLAlchemy |
|-----------------|----------------|
| SQLite (fichier) | `sqlite:///chemin/vers/base.db` |
| SQLite (mémoire) | `sqlite:///:memory:` |
| PostgreSQL | `postgresql+psycopg2://user:pwd@host:5432/db` |
| MySQL | `mysql+pymysql://user:pwd@host/db` |
| SQL Server | `mssql+pyodbc://user:pwd@host/db?driver=...` |

---

## ⚙️ Partie 4 — Configuration et connexion

In [1]:
# ============================================================================
# Imports
# ============================================================================
import sqlite3
import os
from pathlib import Path

import pandas as pd
import numpy as np
from sqlalchemy import create_engine, text

# Configuration pandas pour un meilleur affichage
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 50)
pd.set_option('display.float_format', '{:.2f}'.format)
pd.set_option('display.width', None)

print('✅ Imports réussis')
print(f'  pandas  : {pd.__version__}')
print(f'  numpy   : {np.__version__}')

✅ Imports réussis
  pandas  : 2.2.2
  numpy   : 1.26.4

In [2]:
# ============================================================================
# Chemin vers la base de données
# Ce notebook est dans sql/ — la base sales.db est aussi dans sql/
# ============================================================================
BASE_DIR = Path('.')
DB_PATH  = BASE_DIR / 'sales.db'

# Vérifier que la base existe
if not DB_PATH.exists():
    print(f'❌ Base de données introuvable : {DB_PATH.resolve()}')
    print('   Créez-la avec : sqlite3 sales.db < schema_sales.sql')
    print('   Puis insérez les données : sqlite3 sales.db < insert_sample_data.sql')
else:
    size_kb = DB_PATH.stat().st_size / 1024
    print(f'✅ Base de données trouvée : {DB_PATH.resolve()}')
    print(f'   Taille : {size_kb:.1f} KB')

✅ Base de données trouvée : /home/abraham/Bureau/python-and-data-analysis/sql/sales.db
   Taille : 104.0 KB

In [3]:
# ============================================================================
# Connexion avec SQLAlchemy (approche recommandée)
# ============================================================================

# ----- SQLite (ce notebook) -----
engine = create_engine(f'sqlite:///{DB_PATH}')
print('✅ Engine SQLite créé')
print(f'   URL : {engine.url}')

# ----- PostgreSQL (exemple — ne pas exécuter sans serveur PostgreSQL) -----
# from dotenv import load_dotenv
# load_dotenv()  # Charge les variables depuis .env
#
# PG_URL = (
#     f"postgresql+psycopg2://{os.getenv('PG_USER')}:{os.getenv('PG_PASSWORD')}"
#     f"@{os.getenv('PG_HOST', 'localhost')}:{os.getenv('PG_PORT', 5432)}"
#     f"/{os.getenv('PG_DB')}"
# )
# engine_pg = create_engine(PG_URL)
# print('✅ Engine PostgreSQL créé')
#
# 💡 Conseil : ne jamais écrire vos identifiants dans le code.
#    Utilisez un fichier .env (ajouté dans .gitignore) et python-dotenv.

✅ Engine SQLite créé
   URL : sqlite:///sales.db

In [4]:
# ============================================================================
# Connexion avec sqlite3 natif (approche bas niveau, pour comparaison)
# ============================================================================
conn_sqlite3 = sqlite3.connect(str(DB_PATH))
print('✅ Connexion sqlite3 native créée')

# Vérifier les tables disponibles
cursor = conn_sqlite3.cursor()
cursor.execute("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name;")
tables = cursor.fetchall()
print('\n📋 Tables disponibles :')
for t in tables:
    print(f'   • {t[0]}')

✅ Connexion sqlite3 native créée

📋 Tables disponibles :
   • customer_segments_report
   • customers
   • etl_log
   • monthly_revenue_report
   • order_items
   • orders
   • products
   • products_enriched
   • sqlite_sequence
   • top_products_report

## 📖 Partie 5 — Lire des données avec pandas.read_sql_query

### La fonction clé : `pd.read_sql_query()`

```python
df = pd.read_sql_query(
    sql,           # Requête SQL (string ou objet SQLAlchemy)
    con,           # Connexion (engine SQLAlchemy ou connexion sqlite3)
    params=None,   # Paramètres pour éviter les injections SQL
    parse_dates=None  # Colonnes à parser comme dates
)
```

Le résultat est directement un **DataFrame pandas** — prêt à être analysé, transformé, visualisé.

In [5]:
# ============================================================================
# 5.1 Requête SELECT simple
# ============================================================================
query_customers = """
SELECT
    customer_id,
    first_name,
    last_name,
    email,
    city,
    country,
    created_at
FROM customers
ORDER BY last_name, first_name;
"""

df_customers = pd.read_sql_query(query_customers, engine)

print(f'📊 Shape : {df_customers.shape}')
print(f'   Colonnes : {list(df_customers.columns)}')
df_customers.head()

📊 Shape : (20, 7)
   Colonnes : ['customer_id', 'first_name', 'last_name', 'email', 'city', 'country', 'created_at']

,customer_id,first_name,last_name,email,city,country,created_at
0,3,Pierre,Bernard,pierre.bernard@email.fr,Marseille,France,2026-01-22 17:20:11
1,20,Léa,Bonnet,lea.bonnet@email.fr,Villeurbanne,France,2026-01-22 17:20:11
2,4,Sophie,Dubois,sophie.dubois@email.fr,Toulouse,France,2026-01-22 17:20:11
3,1,Jean,Dupont,jean.dupont@email.fr,Paris,France,2026-01-22 17:20:11
4,9,Paul,Durand,paul.durand@email.fr,Montpellier,France,2026-01-22 17:20:11

In [6]:
# ============================================================================
# 5.2 Informations sur le DataFrame récupéré
# ============================================================================
print('📋 Types de données :')
print(df_customers.dtypes)
print()
print('📊 Statistiques descriptives :')
df_customers.describe(include='all')

📋 Types de données :
customer_id     int64
first_name     object
last_name      object
email          object
city           object
country        object
created_at     object
dtype: object

📊 Statistiques descriptives :

,customer_id,first_name,last_name,email,city,country,created_at
count,20.00,20,20,20,20,20,20
unique,NaN,20,20,20,20,1,1
top,NaN,Pierre,Bernard,pierre.bernard@email.fr,Marseille,France,2026-01-22 17:20:11
freq,NaN,1,1,1,1,20,20
mean,10.50,NaN,NaN,NaN,NaN,NaN,NaN
std,5.92,NaN,NaN,NaN,NaN,NaN,NaN
min,1.00,NaN,NaN,NaN,NaN,NaN,NaN
25%,5.75,NaN,NaN,NaN,NaN,NaN,NaN
50%,10.50,NaN,NaN,NaN,NaN,NaN,NaN
75%,15.25,NaN,NaN,NaN,NaN,NaN,NaN
max,20.00,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
# ============================================================================
# 5.3 Requête avec paramètres — ⚠️ TOUJOURS utiliser des paramètres !
# ============================================================================
# ❌ JAMAIS ça (injection SQL possible) :
# city = input()  # dangereux si l'utilisateur entre : Paris' OR '1'='1
# query = f"SELECT * FROM customers WHERE city = '{city}'"

# ✅ TOUJOURS utiliser des paramètres nommés :
city_filter   = 'Paris'
status_filter = 'delivered'

query_params = """
SELECT
    c.customer_id,
    c.first_name || ' ' || c.last_name AS client,
    c.city,
    COUNT(o.order_id)             AS nb_commandes,
    ROUND(SUM(o.total_amount), 2) AS ca_total
FROM customers c
LEFT JOIN orders o
    ON o.customer_id = c.customer_id
   AND o.status = :status
WHERE c.city = :city
GROUP BY c.customer_id, c.first_name, c.last_name, c.city
ORDER BY ca_total DESC;
"""

df_paris = pd.read_sql_query(
    query_params,
    engine,
    params={'city': city_filter, 'status': status_filter}
)

print(f'👥 Clients de {city_filter} (commandes {status_filter}) :')
df_paris

👥 Clients de Paris (commandes delivered) :

   customer_id       client   city  nb_commandes  ca_total
0            1  Jean Dupont  Paris             2   1429.97

In [8]:
# ============================================================================
# 5.4 parse_dates — Convertir automatiquement les colonnes date
# ============================================================================
df_orders = pd.read_sql_query(
    "SELECT order_id, customer_id, order_date, status, total_amount FROM orders;",
    engine,
    parse_dates=['order_date']
)

print('📋 Types après parse_dates :')
print(df_orders.dtypes)
print(f'\nType de order_date : {df_orders["order_date"].dtype}')
print(f'Plage de dates : {df_orders["order_date"].min()} → {df_orders["order_date"].max()}')
df_orders.head()

📋 Types après parse_dates :
order_id                 int64
customer_id              int64
order_date      datetime64[ns]
status                  object
total_amount           float64
dtype: object

Type de order_date : datetime64[ns]
Plage de dates : 2025-11-05 10:30:00 → 2026-01-22 16:30:00

   order_id  customer_id          order_date     status  total_amount
0         1            1 2025-11-05 10:30:00  delivered       1329.98
1         2            2 2025-11-08 14:22:00  delivered        899.99
2         3            3 2025-11-10 09:15:00  delivered       1698.99
3         4            4 2025-11-12 16:45:00  delivered        199.98
4         5            5 2025-11-15 11:30:00  delivered        379.99

## 🔗 Partie 6 — Requêtes JOIN depuis Python

Les jointures sont le cœur de SQL. Exécutées depuis Python, elles permettent de récupérer des données enrichies directement dans un DataFrame prêt à l'emploi.

In [9]:
# ============================================================================
# 6.1 INNER JOIN — Commandes avec détails client et produits
# ============================================================================
query_join = """
SELECT
    o.order_id,
    o.order_date,
    o.status,
    c.first_name || ' ' || c.last_name  AS customer_name,
    c.city,
    c.email,
    p.product_name,
    p.category,
    oi.quantity,
    oi.unit_price,
    oi.discount_percent,
    oi.subtotal,
    o.payment_method
FROM orders o
INNER JOIN customers   c   ON c.customer_id  = o.customer_id
INNER JOIN order_items oi  ON oi.order_id    = o.order_id
INNER JOIN products    p   ON p.product_id   = oi.product_id
WHERE o.status != 'cancelled'
ORDER BY o.order_date DESC, o.order_id;
"""

df_join = pd.read_sql_query(
    query_join,
    engine,
    parse_dates=['order_date']
)

print(f'📊 Résultat du JOIN : {df_join.shape[0]} lignes × {df_join.shape[1]} colonnes')
df_join.head(10)

📊 Résultat du JOIN : 49 lignes × 13 colonnes

,order_id,order_date,status,customer_name,city,email,product_name,category,quantity,unit_price,discount_percent,subtotal,payment_method
0,39,2026-01-22 15:50:00,pending,Sophie Dubois,Toulouse,sophie.dubois@email.fr,Laptop Dell XPS 13,Électronique,1,1299.99,0,1299.99,Carte bancaire
1,38,2026-01-22 13:20:00,processing,Pierre Bernard,Marseille,pierre.bernard@email.fr,iPad Air,Électronique,1,699.00,0,699.00,PayPal
2,37,2026-01-22 11:30:00,processing,Marie Martin,Lyon,marie.martin@email.fr,Clavier mécanique Logitech,Électronique,1,149.99,0,149.99,Carte bancaire
3,36,2026-01-22 10:45:00,processing,Jean Dupont,Paris,jean.dupont@email.fr,Apple Watch Series 8,Électronique,1,449.00,0,449.00,Carte bancaire
4,35,2026-01-21 14:15:00,processing,Léa Bonnet,Villeurbanne,lea.bonnet@email.fr,"MacBook Pro 14""",Électronique,1,2299.00,0,2299.00,PayPal
5,34,2026-01-21 09:30:00,processing,David Girard,Nîmes,david.girard@email.fr,Aspirateur Dyson V11,Maison,1,599.99,0,599.99,Carte bancaire
6,33,2026-01-20 15:05:00,shipped,Alice Fournier,Angers,alice.fournier@email.fr,Écouteurs Sony WH-1000XM5,Électronique,1,379.99,0,379.99,Carte bancaire
7,32,2026-01-19 10:20:00,shipped,Julien Roux,Dijon,julien.roux@email.fr,iPhone 14 Pro,Électronique,1,1159.00,0,1159.00,PayPal
8,31,2026-01-18 13:45:00,shipped,Sarah Garcia,Grenoble,sarah.garcia@email.fr,Chaussures Nike Air Max,Vêtements,2,139.99,10,279.98,Carte bancaire
9,30,2026-01-16 11:30:00,shipped,Thomas Michel,Toulon,thomas.michel@email.fr,Samsung Galaxy S23,Électronique,1,899.99,0,899.99,Carte bancaire

In [10]:
# ============================================================================
# 6.2 LEFT JOIN — Tous les clients, même sans commande
# ============================================================================
query_left_join = """
SELECT
    c.customer_id,
    c.first_name || ' ' || c.last_name          AS customer_name,
    c.city,
    c.country,
    COUNT(o.order_id)                            AS nb_orders,
    COALESCE(ROUND(SUM(o.total_amount), 2), 0)   AS total_spent,
    MIN(o.order_date)                            AS first_order_date,
    MAX(o.order_date)                            AS last_order_date
FROM customers c
LEFT JOIN orders o
    ON o.customer_id = c.customer_id
   AND o.status != 'cancelled'
GROUP BY c.customer_id, c.first_name, c.last_name, c.city, c.country
ORDER BY total_spent DESC;
"""

df_customers_stats = pd.read_sql_query(
    query_left_join,
    engine,
    parse_dates=['first_order_date', 'last_order_date']
)

print(f'📊 Tous les clients avec statistiques : {df_customers_stats.shape}')
print(f'   Clients avec commandes : {(df_customers_stats["nb_orders"] > 0).sum()}')
print(f'   Clients sans commande  : {(df_customers_stats["nb_orders"] == 0).sum()}')
df_customers_stats.head(10)

📊 Tous les clients avec statistiques : (20, 8)
   Clients avec commandes : 20
   Clients sans commande  : 0

,customer_id,customer_name,city,country,nb_orders,total_spent,first_order_date,last_order_date
0,5,Luc Thomas,Nice,France,3,3978.98,2025-11-15 11:30:00,2026-01-22 16:30:00
1,1,Jean Dupont,Paris,France,3,3728.97,2025-11-05 10:30:00,2026-01-22 10:45:00
2,3,Pierre Bernard,Marseille,France,3,3347.98,2025-11-10 09:15:00,2026-01-22 13:20:00
3,6,Julie Robert,Nantes,France,2,2548.98,2025-11-18 13:20:00,2025-12-25 10:10:00
4,11,Antoine Moreau,Rennes,France,2,2488.00,2025-12-01 10:20:00,2026-01-08 10:40:00
5,8,Claire Petit,Bordeaux,France,2,1998.99,2025-11-22 15:30:00,2025-12-30 09:25:00
6,2,Marie Martin,Lyon,France,3,1528.97,2025-11-08 14:22:00,2026-01-22 11:30:00
7,4,Sophie Dubois,Toulouse,France,3,1178.95,2025-11-12 16:45:00,2026-01-22 15:50:00
8,18,Alice Fournier,Angers,France,1,1159.00,2026-01-20 15:05:00,2026-01-20 15:05:00
9,15,Thomas Michel,Toulon,France,2,1099.98,2025-12-10 09:30:00,2026-01-16 11:30:00

In [11]:
# ============================================================================
# 6.3 Requête analytique — CA par catégorie et par mois
# ============================================================================
query_analytics = """
SELECT
    strftime('%Y-%m', o.order_date) AS year_month,
    p.category,
    COUNT(DISTINCT o.order_id)       AS nb_orders,
    SUM(oi.quantity)                 AS total_qty,
    ROUND(SUM(oi.subtotal), 2)       AS revenue
FROM orders o
INNER JOIN order_items oi ON oi.order_id   = o.order_id
INNER JOIN products    p  ON p.product_id  = oi.product_id
WHERE o.status != 'cancelled'
GROUP BY strftime('%Y-%m', o.order_date), p.category
ORDER BY year_month, revenue DESC;
"""

df_analytics = pd.read_sql_query(query_analytics, engine)
print('📊 CA par catégorie et par mois :')
df_analytics

📊 CA par catégorie et par mois :

  year_month      category  nb_orders  total_qty  revenue
0    2025-11  Électronique          8         10  7956.93
1    2025-11     Vêtements          3          3   199.97
2    2025-11        Livres          1          5   199.95
3    2025-12  Électronique          7          7  6606.96
4    2025-12        Maison          2          2   799.98
5    2025-12     Vêtements          5          6   539.94
6    2025-12        Livres          1          5   209.95
7    2026-01  Électronique         12         12  8963.94
8    2026-01        Maison          2          2  1898.99
9    2026-01     Vêtements          3          8   569.92

## 🧹 Partie 7 — Nettoyage et transformation avec pandas

Une fois les données récupérées de la base, pandas prend le relai pour le nettoyage et l'enrichissement.

In [12]:
# ============================================================================
# 7.1 Inspection du DataFrame brut
# ============================================================================
print('📋 Informations sur df_join :')
df_join.info()
print()
print('🔍 Valeurs manquantes :')
print(df_join.isnull().sum())

📋 Informations sur df_join :
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49 entries, 0 to 48
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          49 non-null     int64
 1   order_date        49 non-null     datetime64[ns]
 2   status            49 non-null     object
 3   customer_name     49 non-null     object
 4   city              49 non-null     object
 5   email             49 non-null     object
 6   product_name      49 non-null     object
 7   category          49 non-null     object
 8   quantity          49 non-null     int64
 9   unit_price        49 non-null     float64
 10  discount_percent  49 non-null     int64
 11  subtotal          49 non-null     float64
 12  payment_method    49 non-null     object
dtypes: datetime64[ns](1), float64(2), int64(3), object(7)
memory usage: 5.1+ KB

🔍 Valeurs manquantes :
order_id            0
order_date          0
status              0
customer_name       0
city                0
email               0
product_name        0
category            0
quantity            0
unit_price          0
discount_percent    0
subtotal            0
payment_method      0
dtype: int64

In [13]:
# ============================================================================
# 7.2 Nettoyage du DataFrame
# ============================================================================
df_clean = df_join.copy()

# --- Convertir order_date en datetime si ce n'est pas déjà fait ---
df_clean['order_date'] = pd.to_datetime(df_clean['order_date'])

# --- Extraire des colonnes utiles depuis la date ---
df_clean['order_year']  = df_clean['order_date'].dt.year
df_clean['order_month'] = df_clean['order_date'].dt.month
df_clean['order_month_name'] = df_clean['order_date'].dt.strftime('%B')
df_clean['order_weekday']    = df_clean['order_date'].dt.day_name()

# --- Normaliser les chaînes de caractères ---
df_clean['customer_name'] = df_clean['customer_name'].str.title().str.strip()
df_clean['category']      = df_clean['category'].str.strip()
df_clean['status']        = df_clean['status'].str.lower().str.strip()

# --- Créer une colonne de remise en euros ---
df_clean['discount_amount'] = (
    df_clean['quantity'] * df_clean['unit_price'] * df_clean['discount_percent'] / 100
).round(2)

# --- Catégoriser les montants ---
df_clean['price_range'] = pd.cut(
    df_clean['subtotal'],
    bins=[0, 50, 100, 200, 500, float('inf')],
    labels=['0-50€', '50-100€', '100-200€', '200-500€', '500€+']
)

print('✅ Nettoyage terminé')
print(f'   Shape : {df_clean.shape}')
print(f'   Nouvelles colonnes : order_year, order_month, order_month_name,')
print(f'                        order_weekday, discount_amount, price_range')
df_clean.head(5)

✅ Nettoyage terminé
   Shape : (49, 19)
   Nouvelles colonnes : order_year, order_month, order_month_name,
                        order_weekday, discount_amount, price_range

,order_id,order_date,status,customer_name,city,email,product_name,category,quantity,unit_price,discount_percent,subtotal,payment_method,order_year,order_month,order_month_name,order_weekday,discount_amount,price_range
0,39,2026-01-22 15:50:00,pending,Sophie Dubois,Toulouse,sophie.dubois@email.fr,Laptop Dell XPS 13,Électronique,1,1299.99,0,1299.99,Carte bancaire,2026,1,January,Thursday,0.00,500€+
1,38,2026-01-22 13:20:00,processing,Pierre Bernard,Marseille,pierre.bernard@email.fr,iPad Air,Électronique,1,699.00,0,699.00,PayPal,2026,1,January,Thursday,0.00,500€+
2,37,2026-01-22 11:30:00,processing,Marie Martin,Lyon,marie.martin@email.fr,Clavier mécanique Logitech,Électronique,1,149.99,0,149.99,Carte bancaire,2026,1,January,Thursday,0.00,100-200€
3,36,2026-01-22 10:45:00,processing,Jean Dupont,Paris,jean.dupont@email.fr,Apple Watch Series 8,Électronique,1,449.00,0,449.00,Carte bancaire,2026,1,January,Thursday,0.00,200-500€
4,35,2026-01-21 14:15:00,processing,Léa Bonnet,Villeurbanne,lea.bonnet@email.fr,"MacBook Pro 14""",Électronique,1,2299.00,0,2299.00,PayPal,2026,1,January,Wednesday,0.00,500€+

In [14]:
# ============================================================================
# 7.3 Analyse : top 10 produits par CA
# ============================================================================
top_products = (
    df_clean
    .groupby(['product_name', 'category'])
    .agg(
        nb_commandes  = ('order_id', 'nunique'),
        total_qty     = ('quantity', 'sum'),
        ca_total      = ('subtotal', 'sum'),
        remise_totale = ('discount_amount', 'sum')
    )
    .round(2)
    .sort_values('ca_total', ascending=False)
    .reset_index()
    .head(10)
)
top_products.columns.name = None
print('🏆 Top 10 produits par chiffre d\'affaires :')
top_products

🏆 Top 10 produits par chiffre d'affaires :

,product_name,category,nb_commandes,total_qty,ca_total,remise_totale
0,"MacBook Pro 14""",Électronique,3,3,6897.00,0.00
1,Laptop Dell XPS 13,Électronique,4,4,5199.96,0.00
2,iPhone 14 Pro,Électronique,2,2,2318.00,0.00
3,iPad Air,Électronique,3,3,2097.00,0.00
4,Samsung Galaxy S23,Électronique,2,2,1799.98,0.00
5,Écouteurs Sony WH-1000XM5,Électronique,4,4,1519.96,19.00
6,"Samsung TV QLED 55""",Électronique,1,1,1499.00,0.00
7,Apple Watch Series 8,Électronique,3,3,1347.00,0.00
8,Robot cuiseur Thermomix,Maison,1,1,1299.00,25.98
9,Aspirateur Dyson V11,Maison,2,2,1199.98,0.00

In [15]:
# ============================================================================
# 7.4 Analyse : segmentation client
# ============================================================================
customer_summary = (
    df_clean
    .groupby('customer_name')
    .agg(
        nb_commandes     = ('order_id', 'nunique'),
        nb_produits      = ('product_name', 'nunique'),
        ca_total         = ('subtotal', 'sum'),
        panier_moyen     = ('subtotal', 'mean'),
        remise_totale    = ('discount_amount', 'sum')
    )
    .round(2)
    .reset_index()
)

# Segmentation sur la base du CA total
def segmenter_client(ca):
    if ca >= 2000:
        return 'VIP'
    elif ca >= 500:
        return 'Régulier'
    elif ca > 0:
        return 'Occasionnel'
    return 'Inactif'

customer_summary['segment'] = customer_summary['ca_total'].apply(segmenter_client)

customer_summary = customer_summary.sort_values('ca_total', ascending=False)
print('👥 Résumé et segmentation des clients :')
print(f'   Répartition par segment :')
print(customer_summary['segment'].value_counts())
customer_summary.head(10)

👥 Résumé et segmentation des clients :
   Répartition par segment :
segment
Régulier       11
VIP             5
Occasionnel     4
Name: count, dtype: int64

,customer_name,nb_commandes,nb_produits,ca_total,panier_moyen,remise_totale,segment
16,Pierre Bernard,3,5,3907.97,781.59,19.00,VIP
10,Luc Thomas,2,2,2678.99,1339.50,0.00,VIP
7,Julie Robert,2,3,2548.98,849.66,0.00,VIP
1,Antoine Moreau,2,3,2487.99,829.33,25.98,VIP
11,Léa Bonnet,1,1,2299.00,2299.00,0.00,VIP
3,Claire Petit,2,2,1998.99,999.50,0.00,Régulier
6,Jean Dupont,3,4,1878.97,469.74,0.00,Régulier
18,Sophie Dubois,3,4,1779.91,444.98,0.00,Régulier
13,Marie Martin,3,4,1229.96,307.49,0.00,Régulier
8,Julien Roux,1,1,1159.00,1159.00,0.00,Régulier

In [16]:
# ============================================================================
# 7.5 Analyse : evolution mensuelle du CA
# ============================================================================
monthly_revenue = (
    df_clean
    .groupby(['order_year', 'order_month', 'order_month_name'])
    .agg(
        nb_commandes   = ('order_id', 'nunique'),
        nb_clients     = ('customer_name', 'nunique'),
        ca_total       = ('subtotal', 'sum'),
        panier_moyen   = ('subtotal', lambda x: x.sum() / df_clean.loc[x.index, 'order_id'].nunique())
    )
    .round(2)
    .reset_index()
    .sort_values(['order_year', 'order_month'])
)
print('📅 CA mensuel :')
monthly_revenue

📅 CA mensuel :

,order_year,order_month,order_month_name,nb_commandes,nb_clients,ca_total,panier_moyen
0,2025,11,November,10,10,8356.85,835.68
1,2025,12,December,13,13,8156.83,627.45
2,2026,1,January,16,16,11432.85,714.55

## 💾 Partie 8 — Écrire des données dans la base

### `df.to_sql()` — La méthode pandas pour écrire en base

```python
df.to_sql(
    name,              # Nom de la table
    con,               # Engine SQLAlchemy
    if_exists='fail',  # 'fail', 'replace', 'append'
    index=True,        # Inclure l'index comme colonne ?
    dtype=None,        # Types SQL explicites (optionnel)
    chunksize=None     # Écrire par morceaux (grandes tables)
)
```

| `if_exists` | Comportement |
|-------------|-------------|
| `'fail'`    | Lève une erreur si la table existe déjà |
| `'replace'` | Supprime et recrée la table |
| `'append'`  | Ajoute les lignes à la table existante |

In [17]:
# ============================================================================
# 8.1 Écrire le top 10 produits dans la base
# ============================================================================
top_products.to_sql(
    name      = 'top_products_report',
    con       = engine,
    if_exists = 'replace',   # Remplacer si la table existe
    index     = False        # Ne pas inclure l'index pandas
)

print('✅ Table "top_products_report" créée dans la base')

# Vérifier en relisant
df_check = pd.read_sql_query('SELECT * FROM top_products_report;', engine)
print(f'   Lignes relues : {len(df_check)}')
df_check

✅ Table "top_products_report" créée dans la base
   Lignes relues : 10

,product_name,category,nb_commandes,total_qty,ca_total,remise_totale
0,"MacBook Pro 14""",Électronique,3,3,6897.00,0.00
1,Laptop Dell XPS 13,Électronique,4,4,5199.96,0.00
2,iPhone 14 Pro,Électronique,2,2,2318.00,0.00
3,iPad Air,Électronique,3,3,2097.00,0.00
4,Samsung Galaxy S23,Électronique,2,2,1799.98,0.00
5,Écouteurs Sony WH-1000XM5,Électronique,4,4,1519.96,19.00
6,"Samsung TV QLED 55""",Électronique,1,1,1499.00,0.00
7,Apple Watch Series 8,Électronique,3,3,1347.00,0.00
8,Robot cuiseur Thermomix,Maison,1,1,1299.00,25.98
9,Aspirateur Dyson V11,Maison,2,2,1199.98,0.00

In [18]:
# ============================================================================
# 8.2 Écrire la segmentation client dans la base
# ============================================================================
customer_summary.to_sql(
    name      = 'customer_segments_report',
    con       = engine,
    if_exists = 'replace',
    index     = False
)

print('✅ Table "customer_segments_report" créée dans la base')

# Vérifier le nombre de lignes
count = pd.read_sql_query('SELECT COUNT(*) AS n FROM customer_segments_report;', engine)
print(f'   Lignes écrites : {count["n"][0]}')

✅ Table "customer_segments_report" créée dans la base
   Lignes écrites : 20

In [19]:
# ============================================================================
# 8.3 Écrire avec contrôle des types SQL (exemple avancé)
# ============================================================================
from sqlalchemy import Integer, String, Float, DateTime

monthly_revenue.to_sql(
    name      = 'monthly_revenue_report',
    con       = engine,
    if_exists = 'replace',
    index     = False,
    dtype     = {
        'order_year'     : Integer(),
        'order_month'    : Integer(),
        'order_month_name': String(20),
        'nb_commandes'   : Integer(),
        'nb_clients'     : Integer(),
        'ca_total'       : Float(),
        'panier_moyen'   : Float()
    }
)

print('✅ Table "monthly_revenue_report" créée avec types SQL explicites')
pd.read_sql_query('SELECT * FROM monthly_revenue_report;', engine)

✅ Table "monthly_revenue_report" créée avec types SQL explicites

,order_year,order_month,order_month_name,nb_commandes,nb_clients,ca_total,panier_moyen
0,2025,11,November,10,10,8356.85,835.68
1,2025,12,December,13,13,8156.83,627.45
2,2026,1,January,16,16,11432.85,714.55

In [20]:
# ============================================================================
# 8.4 Utiliser execute() pour des opérations DML (INSERT / UPDATE / DELETE)
# ============================================================================
# Exemple : UPDATE direct via SQLAlchemy
with engine.begin() as conn:
    # Créer une table de log si nécessaire
    conn.execute(text("""
        CREATE TABLE IF NOT EXISTS etl_log (
            log_id      INTEGER PRIMARY KEY AUTOINCREMENT,
            run_date    TEXT    DEFAULT (datetime('now')),
            table_name  TEXT    NOT NULL,
            rows_loaded INTEGER NOT NULL,
            status      TEXT    DEFAULT 'success'
        );
    """))

    # Enregistrer les métadonnées de notre run
    conn.execute(text("""
        INSERT INTO etl_log (table_name, rows_loaded)
        VALUES ('top_products_report', :n_rows);
    """), {'n_rows': len(top_products)})

print('✅ Log ETL enregistré dans la table etl_log')

pd.read_sql_query('SELECT * FROM etl_log;', engine)

✅ Log ETL enregistré dans la table etl_log

   log_id             run_date           table_name  rows_loaded   status
0       1  2026-04-19 15:00:46  top_products_report           10  success
1       2  2026-04-19 16:18:05  top_products_report           10  success

## 📁 Partie 9 — Exercice livrable : JOIN → pandas → CSV

### Énoncé

> **Objectif** : Exécuter une requête JOIN complète depuis Python, nettoyer le résultat dans pandas, puis l'enregistrer en CSV.
>
> La requête doit joindre au moins 3 tables : `orders`, `customers`, `order_items`, `products`.  
> Le CSV final doit être propre : colonnes renommées, types corrects, pas de doublons, valeurs null gérées.

In [21]:
# ============================================================================
# ÉTAPE 1 : Requête JOIN complète (4 tables)
# ============================================================================
query_exercise = """
SELECT
    o.order_id                              AS id_commande,
    o.order_date                            AS date_commande,
    o.status                                AS statut,
    c.first_name || ' ' || c.last_name      AS nom_client,
    c.email                                 AS email_client,
    c.city                                  AS ville,
    c.country                               AS pays,
    p.product_name                          AS produit,
    p.category                              AS categorie,
    p.supplier                              AS fournisseur,
    oi.quantity                             AS quantite,
    oi.unit_price                           AS prix_unitaire,
    oi.discount_percent                     AS remise_pct,
    oi.subtotal                             AS sous_total,
    o.payment_method                        AS mode_paiement
FROM orders o
INNER JOIN customers   c   ON c.customer_id = o.customer_id
INNER JOIN order_items oi  ON oi.order_id   = o.order_id
INNER JOIN products    p   ON p.product_id  = oi.product_id
WHERE o.status IN ('delivered', 'shipped')
ORDER BY o.order_date DESC, o.order_id, p.product_name;
"""

df_exercise = pd.read_sql_query(
    query_exercise,
    engine,
    parse_dates=['date_commande']
)

print(f'✅ ÉTAPE 1 — Résultat du JOIN : {df_exercise.shape}')
df_exercise.head(8)

✅ ÉTAPE 1 — Résultat du JOIN : (43, 15)

,id_commande,date_commande,statut,nom_client,email_client,ville,pays,produit,categorie,fournisseur,quantite,prix_unitaire,remise_pct,sous_total,mode_paiement
0,33,2026-01-20 15:05:00,shipped,Alice Fournier,alice.fournier@email.fr,Angers,France,Écouteurs Sony WH-1000XM5,Électronique,Sony Corporation,1,379.99,0,379.99,Carte bancaire
1,32,2026-01-19 10:20:00,shipped,Julien Roux,julien.roux@email.fr,Dijon,France,iPhone 14 Pro,Électronique,Apple Inc.,1,1159.00,0,1159.00,PayPal
2,31,2026-01-18 13:45:00,shipped,Sarah Garcia,sarah.garcia@email.fr,Grenoble,France,Chaussures Nike Air Max,Vêtements,Nike,2,139.99,10,279.98,Carte bancaire
3,30,2026-01-16 11:30:00,shipped,Thomas Michel,thomas.michel@email.fr,Toulon,France,Samsung Galaxy S23,Électronique,Samsung Electronics,1,899.99,0,899.99,Carte bancaire
4,29,2026-01-14 16:10:00,shipped,Laura Lefebvre,laura.lefebvre@email.fr,Saint-Étienne,France,Pull H&M en laine,Vêtements,H&M,1,39.99,0,39.99,PayPal
5,29,2026-01-14 16:10:00,shipped,Laura Lefebvre,laura.lefebvre@email.fr,Saint-Étienne,France,T-shirt Nike Sportswear,Vêtements,Nike,2,29.99,0,59.98,PayPal
6,29,2026-01-14 16:10:00,shipped,Laura Lefebvre,laura.lefebvre@email.fr,Saint-Étienne,France,Veste Adidas à capuche,Vêtements,Adidas,2,79.99,15,159.98,PayPal
7,28,2026-01-12 09:50:00,shipped,Nicolas Laurent,nicolas.laurent@email.fr,Le Havre,France,Souris Logitech MX Master 3,Électronique,Logitech,1,99.99,0,99.99,Carte bancaire

In [22]:
# ============================================================================
# ÉTAPE 2 : Nettoyage dans pandas
# ============================================================================
df_result = df_exercise.copy()

# 1. Vérifier les doublons
n_dupes = df_result.duplicated().sum()
print(f'   Doublons détectés : {n_dupes}')

# 2. Vérifier les valeurs nulles
nulls = df_result.isnull().sum()
print(f'   Valeurs nulles par colonne :')
print(nulls[nulls > 0] if nulls.any() else '   → Aucune valeur nulle 👍')

# 3. Normaliser les chaînes
df_result['nom_client']  = df_result['nom_client'].str.title().str.strip()
df_result['statut']      = df_result['statut'].str.capitalize()
df_result['categorie']   = df_result['categorie'].str.strip()
df_result['fournisseur'] = df_result['fournisseur'].str.strip()

# 4. Colonnes dérivées
df_result['annee']           = df_result['date_commande'].dt.year
df_result['mois']            = df_result['date_commande'].dt.month
df_result['remise_euros']    = (df_result['quantite'] * df_result['prix_unitaire'] * df_result['remise_pct'] / 100).round(2)

# 5. Trier
df_result = df_result.sort_values(['date_commande', 'id_commande']).reset_index(drop=True)

print(f'\n✅ ÉTAPE 2 — DataFrame nettoyé : {df_result.shape}')
print(f'   Colonnes finales : {list(df_result.columns)}')
df_result.head(5)

   Doublons détectés : 0
   Valeurs nulles par colonne :
   → Aucune valeur nulle 👍

✅ ÉTAPE 2 — DataFrame nettoyé : (43, 18)
   Colonnes finales : ['id_commande', 'date_commande', 'statut', 'nom_client', 'email_client', 'ville', 'pays', 'produit', 'categorie', 'fournisseur', 'quantite', 'prix_unitaire', 'remise_pct', 'sous_total', 'mode_paiement', 'annee', 'mois', 'remise_euros']

,id_commande,date_commande,statut,nom_client,email_client,ville,pays,produit,categorie,fournisseur,quantite,prix_unitaire,remise_pct,sous_total,mode_paiement,annee,mois,remise_euros
0,1,2025-11-05 10:30:00,Delivered,Jean Dupont,jean.dupont@email.fr,Paris,France,Laptop Dell XPS 13,Électronique,Dell Inc.,1,1299.99,0,1299.99,Carte bancaire,2025,11,0.00
1,1,2025-11-05 10:30:00,Delivered,Jean Dupont,jean.dupont@email.fr,Paris,France,T-shirt Nike Sportswear,Vêtements,Nike,1,29.99,0,29.99,Carte bancaire,2025,11,0.00
2,2,2025-11-08 14:22:00,Delivered,Marie Martin,marie.martin@email.fr,Lyon,France,Samsung Galaxy S23,Électronique,Samsung Electronics,1,899.99,0,899.99,PayPal,2025,11,0.00
3,3,2025-11-10 09:15:00,Delivered,Pierre Bernard,pierre.bernard@email.fr,Marseille,France,Laptop Dell XPS 13,Électronique,Dell Inc.,1,1299.99,0,1299.99,Carte bancaire,2025,11,0.00
4,3,2025-11-10 09:15:00,Delivered,Pierre Bernard,pierre.bernard@email.fr,Marseille,France,T-shirt Nike Sportswear,Vêtements,Nike,1,29.99,0,29.99,Carte bancaire,2025,11,0.00

In [23]:
# ============================================================================
# ÉTAPE 3 : Enregistrer en CSV
# ============================================================================
output_dir = Path('.')
csv_path   = output_dir / 'orders_cleaned_s13.csv'

df_result.to_csv(
    csv_path,
    index     = False,
    encoding  = 'utf-8-sig',   # BOM pour compatibilité Excel
    sep       = ',',
    date_format = '%Y-%m-%d'
)

print(f'✅ ÉTAPE 3 — CSV exporté : {csv_path.resolve()}')
print(f'   Lignes  : {len(df_result)}')
print(f'   Colonnes: {len(df_result.columns)}')
print(f'   Taille  : {csv_path.stat().st_size / 1024:.1f} KB')

# Relire pour vérification
df_reload = pd.read_csv(csv_path, parse_dates=['date_commande'])
print(f'\n🔍 Vérification après rechargement : {df_reload.shape}')
df_reload.head(3)

✅ ÉTAPE 3 — CSV exporté : /home/abraham/Bureau/python-and-data-analysis/sql/orders_cleaned_s13.csv
   Lignes  : 43
   Colonnes: 18
   Taille  : 6.9 KB

🔍 Vérification après rechargement : (43, 18)

,id_commande,date_commande,statut,nom_client,email_client,ville,pays,produit,categorie,fournisseur,quantite,prix_unitaire,remise_pct,sous_total,mode_paiement,annee,mois,remise_euros
0,1,2025-11-05,Delivered,Jean Dupont,jean.dupont@email.fr,Paris,France,Laptop Dell XPS 13,Électronique,Dell Inc.,1,1299.99,0,1299.99,Carte bancaire,2025,11,0.00
1,1,2025-11-05,Delivered,Jean Dupont,jean.dupont@email.fr,Paris,France,T-shirt Nike Sportswear,Vêtements,Nike,1,29.99,0,29.99,Carte bancaire,2025,11,0.00
2,2,2025-11-08,Delivered,Marie Martin,marie.martin@email.fr,Lyon,France,Samsung Galaxy S23,Électronique,Samsung Electronics,1,899.99,0,899.99,PayPal,2025,11,0.00

In [24]:
# ============================================================================
# Bonus — Plusieurs exports : CSV par statut, Excel multi-feuilles
# ============================================================================

# Export CSV par statut
for statut, groupe in df_result.groupby('statut'):
    fname = output_dir / f'orders_{statut.lower()}_s13.csv'
    groupe.to_csv(fname, index=False, encoding='utf-8-sig')
    print(f'  📄 {fname.name} — {len(groupe)} lignes')

# Export Excel multi-feuilles (nécessite openpyxl)
try:
    excel_path = output_dir / 'rapport_s13.xlsx'
    with pd.ExcelWriter(excel_path, engine='openpyxl') as writer:
        df_result.to_excel(writer, sheet_name='Détail commandes', index=False)
        top_products.to_excel(writer, sheet_name='Top produits', index=False)
        customer_summary.to_excel(writer, sheet_name='Clients', index=False)
        monthly_revenue.to_excel(writer, sheet_name='CA mensuel', index=False)
    print(f'\n📊 Excel exporté : {excel_path.name} (4 feuilles)')
except ImportError:
    print('💡 Pour exporter en Excel : pip install openpyxl')

  📄 orders_delivered_s13.csv — 32 lignes
  📄 orders_shipped_s13.csv — 11 lignes

📊 Excel exporté : rapport_s13.xlsx (4 feuilles)

## 🔄 Partie 10 — Mixte : pandas ↔ base de données

L'intérêt de SQLAlchemy + pandas est de pouvoir **alterner** librement entre la base et Python.

In [25]:
# ============================================================================
# Workflow ETL complet :
# 1. Lire depuis la base
# 2. Transformer dans pandas
# 3. Réécrire dans la base
# ============================================================================

# --- 1. Lire ---
df_products_raw = pd.read_sql_query(
    "SELECT product_id, product_name, category, price, stock_quantity FROM products;",
    engine
)
print(f'🔽 Lu depuis la base : {df_products_raw.shape}')

# --- 2. Transformer ---
df_products_enriched = df_products_raw.copy()

# Valeur totale du stock par produit
df_products_enriched['stock_value'] = (
    df_products_enriched['price'] * df_products_enriched['stock_quantity']
).round(2)

# Alerte stock faible
df_products_enriched['low_stock_alert'] = df_products_enriched['stock_quantity'] < 15

# Gamme de prix
df_products_enriched['price_tier'] = pd.cut(
    df_products_enriched['price'],
    bins=[0, 50, 200, 500, float('inf')],
    labels=['Entrée de gamme', 'Milieu de gamme', 'Haut de gamme', 'Premium']
).astype(str)

print(f'🔧 Transformé : {df_products_enriched.shape}')
print(f'   Produits en alerte stock : {df_products_enriched["low_stock_alert"].sum()}')

# --- 3. Réécrire ---
df_products_enriched.to_sql(
    'products_enriched',
    engine,
    if_exists='replace',
    index=False
)
print(f'🔼 Réécrit dans la base : table "products_enriched"')
df_products_enriched.head()

🔽 Lu depuis la base : (30, 5)
🔧 Transformé : (30, 8)
   Produits en alerte stock : 3
🔼 Réécrit dans la base : table "products_enriched"

,product_id,product_name,category,price,stock_quantity,stock_value,low_stock_alert,price_tier
0,1,Laptop Dell XPS 13,Électronique,1299.99,15,19499.85,False,Premium
1,2,iPhone 14 Pro,Électronique,1159.00,25,28975.00,False,Premium
2,3,Samsung Galaxy S23,Électronique,899.99,20,17999.80,False,Premium
3,4,iPad Air,Électronique,699.00,18,12582.00,False,Premium
4,5,Écouteurs Sony WH-1000XM5,Électronique,379.99,30,11399.70,False,Haut de gamme

In [26]:
# ============================================================================
# Vérification finale : lister toutes les tables (y compris les nouvelles)
# ============================================================================
df_all_tables = pd.read_sql_query(
    "SELECT name, type FROM sqlite_master WHERE type IN ('table','view') ORDER BY type, name;",
    engine
)

print('📋 Contenu de la base après la session :')
df_all_tables

📋 Contenu de la base après la session :

                        name   type
0   customer_segments_report  table
1                  customers  table
2                    etl_log  table
3     monthly_revenue_report  table
4                order_items  table
5                     orders  table
6                   products  table
7          products_enriched  table
8            sqlite_sequence  table
9        top_products_report  table
10             order_summary   view
11             product_sales   view

## 🛡️ Partie 11 — Bonnes pratiques et sécurité

### 11.1 Toujours fermer vos connexions

```python
# ✅ Bonne pratique : utiliser un context manager
with engine.connect() as conn:
    df = pd.read_sql_query(query, conn)
# La connexion est automatiquement fermée ici
```

### 11.2 Ne jamais écrire vos mots de passe dans le code

```python
# ✅ Utiliser des variables d'environnement
import os
from dotenv import load_dotenv

load_dotenv()  # Charge depuis .env (jamais commité dans Git !)

engine = create_engine(
    f"postgresql+psycopg2://{os.getenv('DB_USER')}:{os.getenv('DB_PASSWORD')}"
    f"@{os.getenv('DB_HOST')}/{os.getenv('DB_NAME')}"
)
```

Exemple de fichier `.env` :
```
DB_USER=mon_utilisateur
DB_PASSWORD=mon_mot_de_passe
DB_HOST=localhost
DB_NAME=sales_db
```

Et dans `.gitignore` :
```
.env
*.db
```

### 11.3 Paramétrer toujours vos requêtes

```python
# ❌ Risque d'injection SQL
query = f"SELECT * FROM users WHERE name = '{user_input}'"

# ✅ Toujours utiliser des paramètres
df = pd.read_sql_query(
    "SELECT * FROM users WHERE name = :name",
    engine,
    params={'name': user_input}
)
```

### 11.4 Utiliser des transactions pour les écritures

```python
# ✅ engine.begin() = transaction automatique (commit ou rollback)
with engine.begin() as conn:
    conn.execute(text("UPDATE products SET price = :price WHERE product_id = :id"),
                 {'price': 99.99, 'id': 1})
    conn.execute(text("INSERT INTO audit_log (action) VALUES ('price_update')"))
# Si une erreur survient → rollback automatique
# Sinon → commit automatique
```

In [27]:
# ============================================================================
# Nettoyage final : fermer les connexions
# ============================================================================
conn_sqlite3.close()
engine.dispose()

print('✅ Toutes les connexions fermées proprement')
print()
print('📦 Fichiers produits dans ce notebook :')
for f in Path('.').glob('*_s13*'):
    size = f.stat().st_size / 1024
    print(f'   📄 {f.name} ({size:.1f} KB)')

✅ Toutes les connexions fermées proprement

📦 Fichiers produits dans ce notebook :
   📄 sql_python_s13.ipynb (47.9 KB)
   📄 orders_cleaned_s13.csv (6.9 KB)
   📄 rapport_s13.xlsx (12.5 KB)
   📄 orders_delivered_s13.csv (5.5 KB)
   📄 orders_shipped_s13.csv (2.0 KB)

## 📚 Partie 12 — Récapitulatif et ressources

### Ce que vous avez appris

| Concept | Outil | Cas d'usage |
|---------|-------|-------------|
| Connexion DB | `sqlalchemy.create_engine()` | SQLite, PostgreSQL, MySQL… |
| Lire des données | `pd.read_sql_query()` | Requêtes SELECT, JOIN |
| Paramétrer les requêtes | `params={...}` | Sécurité, réutilisabilité |
| Parser les dates | `parse_dates=[...]` | Colonnes datetime |
| Écrire en base | `df.to_sql()` | Résultats transformés |
| Exécuter DML | `engine.begin()` + `text()` | INSERT, UPDATE, DELETE |
| Exporter CSV | `df.to_csv()` | Livraison de rapports |
| Exporter Excel | `pd.ExcelWriter()` | Rapports multi-feuilles |

### Workflow type de l'analyste de données

```
Base de données (source de vérité)
         │
         │  pd.read_sql_query()  ← requêtes JOIN complexes
         ▼
    DataFrame pandas
         │
         ├── Nettoyage (isnull, dropna, astype, str.strip...)
         ├── Transformation (groupby, merge, apply, cut...)
         ├── Analyse (describe, value_counts, corr...)
         ├── Visualisation (matplotlib, seaborn, plotly)
         │
         ├── df.to_sql()   → Résultats enrichis dans la base
         └── df.to_csv()   → Livraison de rapports
```

### Ressources

- 📖 [SQLAlchemy Documentation](https://docs.sqlalchemy.org/)
- 📖 [pandas.read_sql_query](https://pandas.pydata.org/docs/reference/api/pandas.read_sql_query.html)
- 📖 [pandas.DataFrame.to_sql](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_sql.html)
- 📖 [psycopg2 Documentation](https://www.psycopg.org/docs/)
- 📖 [python-dotenv](https://pypi.org/project/python-dotenv/)

---

**Grow Up AI** — Formation Python & Analyse de Données  
*Session 13 — SQL depuis Python*